language: node_js
node_js:
- 'node'
sudo: false
before_install:
- npm install -g npm@next
before_script:
- npm install -g grunt-cli
script:
- grunt test
before_deploy:
- grunt replace:version --tag=$TRAVIS_TAG --build=$TRAVIS_BUILD_NUMBER
- npm unpublish emp.ria-jsbuild3@$TRAVIS_TAG
deploy:
  provider: npm
  email: viatsyshyn@gmail.com
  api_key:
    secure: "0Hehdjc/HSwCzDbZotnBQTWDDc6PsCiDGy+5VYg57VqKifAt5wxtOAfZeLyj5co5cLEIEYMEcrckk3YQqAwDlDlXcDqxFmDsyC2fP00zhPmu5d/mHhCw6DRmgKv6k9BEbUYmbTwzwO3G91IimbWKQ0XXeDSnHIiXq0AIv0Xga7dUWt9WgYU4P/T6WMZbZvKcfrDGKiV6UcDSn3LtSEkD0hgDQPVNo3gPsFRigUdbohvBvQcKrsJaABh5IC4qaDAEfpgxC2hZX7sANJO6QCjG8hdZFxGstILJ1lXNzDZv1lN2XYTWYuR5DBfj9FqUWNyNE0nk70VWjWvwtBaZaY05F9fYpRdd1KugCW7CbBwVHkPtAS76TRH6sgTBl8JaSmu34PpYCP6ytmtbu61OZA7lOMizDLyBwLJmCyPAmPFGnGNZ+nUuNLqUbQiKe3mMWo5aYdTbHf37DJsvzGSVnunPhKB+PppmQYAHbV5ZvZcIsfqcm9GnVQvbIq0B1Mv6hKoBazc3EpBJdZxeFFVhvVMD+DZ9tyRmIv0v/fj1GxBElu//x0PztCCnCf0Wr2VFRhalLB74huDicgQLirhDbAHA6outWHQNQKcL4+NPJhTFxEmGi5ua5+VQl2mAhu4kUsjU0D8AiYuy+HJba3S/CbLJgVmGtYO+MMQjt8AWmliql2A="  skip_cleanup: true
  skip_cleanup: true
  on:
    tags: true
    repo: viatsyshyn/jsbuild3
